services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - timezone=${TIMEZONE:-America/Chicago}
        - port=${PORT:-80}
    command: npm run ${MODE:-DEV}
    container_name: 
    environment:
      - TIMEZONE=${TIMEZONE:-America/Chicago}
      - PORT=${PORT:-80}
      - USER_AGENT=${user_agent}
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://app:${PORT:-80} || exit 1"
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
    init: true
    ports:
      - "${PORT:-80}:${PORT:-80}"
    restart: unless-stopped
    security_opt: 
      - seccomp=chrome.json
    user: "user:user"
    volumes:
      - sessions:/usr/app/backend/sessions/
      - .:/usr/app/
volumes:
    sessions:
        external: false